# VERSÃO: v25
name: universidade_lideres_app
description: "Aplicativo nativo da Universidade de Líderes."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.14.2
  video_player: ^2.11.1
  cached_network_image: ^3.4.1
  media_kit: ^1.2.6
  media_kit_video: ^2.0.1
  media_kit_libs_video: ^1.0.7
  url_launcher: ^6.3.2
  path_provider: ^2.1.6
  flutter_file_dialog: 3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icons/icone.png"
  remove_alpha_ios: true
  background_color_ios: "#050609"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/images/
